services:
  stt-service:
    build: stt-service
    ports:
      - "8001:8001"
    environment:
      STT_MODEL_PATH: /models/ggml-large-v3.bin
    volumes:
      - whisper-models:/models
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    #  - render

volumes:
  whisper-models:
